# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='administrator',
            options={'permissions': (('move_post', 'Move the post'), ('delete_post', 'Delete the post'), ('ban_post', 'Banned specified user to post'), ('ban_user', 'Banned specified user to visit'))},
        ),
        migrations.AddField(
            model_name='administrator',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='block',
            field=models.ManyToManyField(related_name='block', to='backendSys.Choices'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='permission',
            field=models.ManyToManyField(related_name='permission', to='backendSys.Choices'),
        ),
    ]
