# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 13:14
from __future__ import unicode_literals

import bbs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20171201_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='upload_imgs/user-1.jpg', height_field=60, upload_to=bbs.models.user_directory_path),
        ),
    ]
