# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20171201_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo',
            new_name='headImage',
        ),
    ]
