# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0009_auto_20171201_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('edit_profile', 'Edit profile'),)},
        ),
    ]
