# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_auto_20171228_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='bbs.Article'),
        ),
    ]
