# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_auto_20171229_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phoneNum',
            field=models.CharField(blank=True, help_text='长号', max_length=11, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_dynamic',
            field=models.CharField(choices=[('AL', 'Receive all dynamic'), ('FL', 'Receive follow dynamic')], default='AL', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_email',
            field=models.CharField(choices=[('AM', 'Receive all email'), ('EM', 'Receive unread email'), ('NM', 'Receive no email')], default='AM', max_length=2),
        ),
    ]
