# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0014_auto_20180101_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('MN', '男'), ('WM', '女'), ('SY', '保密')], default='SY', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='receive_dynamic',
            field=models.CharField(choices=[('AL', '所有人'), ('FL', '关注的人')], default='AL', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='receive_email',
            field=models.CharField(choices=[('AM', '所有邮件'), ('EM', '未读邮件'), ('NM', '不接受')], default='AM', max_length=2),
        ),
    ]
