# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 03:41
from __future__ import unicode_literals

import bbs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0015_auto_20180101_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='headImage',
            field=models.ImageField(default='static/picture/zwei_art.jpg', upload_to=bbs.models.user_directory_path),
        ),
    ]
