# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0017_userprofile_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='admin',
            field=models.ManyToManyField(related_name='category', to='bbs.UserProfile', verbose_name='模块管理员'),
        ),
    ]
