# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
