# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='follower_id',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='username',
            new_name='user_id',
        ),
    ]
