# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0015_auto_20180101_0236'),
        ('personalProfile', '0004_followship'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacker', to='bbs.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentUser', to='bbs.UserProfile')),
            ],
        ),
    ]
