# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalProfile', '0005_blacklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='user',
            new_name='currentUser',
        ),
    ]
